### ISSUE TITLE
CTM not working

### ISSUE THREAD

**Issue by 5hinySylveon** [CyanideX/Unity-Extras#10]
Whenever I turn on Unity-Extras, I get the missing textures for many blocks, I've tried to uninstall and reinstal Unity, check if there was an update, see if any of my texture packs are incompatible. Every other Unity pack works except for extras 
![Unity broke](https://user-images.githubusercontent.com/106100669/169860786-2a3b2ee8-c205-4c14-862c-bc8a3eb05586.png)

**Comment by 5hinySylveon** [comment]
Version is 1.18.2

**Comment by CyanideX** [comment]
From the issue report template:
> **Additional Context**
> Add any other context about the problem here. Do you happen to have any mods installed? Do you have any other resource packs enabled? Are you using OptiFine?

I need to know more because it's working fine for me in 1.18.2:
![image](https://user-images.githubusercontent.com/3106700/169871050-43f7167e-0da4-40ef-a0a5-3dc7b7c5aac8.png)

**Comment by 5hinySylveon** [comment]
Im using sodium and other performance mods along with continuity, until recently everything was working fine. If you wish I can send you screenshots of all the mods I have installed

**Comment by CyanideX** [comment]
Yes, please send screenshots. That is why it is best to follow the issue template when submitting issues because most of the info I needed is listed there. 😉

**Comment by 5hinySylveon** [comment]
![image](https://user-images.githubusercontent.com/106100669/169884209-f03e20d6-0eb7-48d9-8f0a-b70fee7669db.png)
![image](https://user-images.githubusercontent.com/106100669/169884240-d2c1c19f-afb9-4059-9bdc-0410f16aebe1.png)
I've taken a screenshot of resource packs too, in case that's needed

**Comment by CyanideX** [comment]
Unity Extras depends on OptiFine or ConnectedTexturesMod (CTM) for most of its features, as stated in the project description.

**Comment by 5hinySylveon** [comment]
Is it not compatible with continuity? It worked beforehand so I dont understand why it isnt now

**Comment by CyanideX** [comment]
It seems the issue is with one of the mods in your pack (or a config) so my only suggestion would be to remove all the mods and add them back one at a time until Unity breaks again and then let me know so I can look into it. Sorry I don't have an immediate answer.

**Comment by CyanideX** [comment]
Does changing the order of your resource packs do anything? Have you tried putting Unity Extras at the top?

**Comment by 5hinySylveon** [comment]
Nope, just seems to be extras thats broken, I removed every texture pack and only put in unity and unity extra, even put extras at the top

**Comment by CyanideX** [comment]
I said remove all **_mods_**, not resource packs; one of the mods is most likely causing the issue.

**Comment by 5hinySylveon** [comment]
oh sorry my bad, miscommunication

**Comment by 5hinySylveon** [comment]
Sorry for a late response, but it seems to be sodium, I remove sodium and Unity Extra's works. I dont know if this a sodium bug or Unity is just incompatible.
