### ISSUE TITLE
[1.16.5] Clear glass and glass panes render as water when using SEUS PTGI shaders

### ISSUE THREAD

**Issue by Crawmak** [CyanideX/Unity-Extras#8]
**Describe the Issue**
As the title says. Specifically the clear variants of glass blocks and panes are shown with animated waves as if it was water, specifically when using SEUS PTGI shaders. (Version 2.1 if that's important)

**To Reproduce**
1. Enable Unity Extras in your resource packs menu, with or without the Unity PBR textures.
2. Enable SEUS PTGI shaders via OptiFine's shader menu. 
3. Observe! Your glass is now water. Not stained glass though. That's still glass. 

**Expected Behavior**
A clear and concise glass block.

Pictured: Clear glass (Left), white stained glass (right)
![2021-02-18_15 35 14](https://user-images.githubusercontent.com/79285056/108424553-f28eaa80-71fe-11eb-96a2-577f27817ce3.png)

**Comment by CyanideX** [comment]
That's a SEUS bug, unfortunately; I can't do anything about it.
